### PR TITLE
#146: Added boolean parameter use-node-name-as-external-address, defa…

### LINKED ISSUE #146: NodePort Service Requires Access to /nodes Kubernetes Resource
I'm trying to configure Hazelcast clients outside the Kubernetes cluster where our service is running embedded Hazelcast nodes. We are running in a shared Kubernetes cluster, where we have access only to our own namespaces. We do not have access to LoadBalancer services, so I'm using NodePort services to expose Hazelcast to the clients.

The service account I'm using currently does not have access to the `/nodes` resource. This means that the Hazelcast client connection fails in `KubernetesClient.enrichWithPublicAddresses` when calling `extractNodePublicIp(callGet(nodeUrl))`; the `callGet` method fails with HTTP 403 Forbidden.

I guess someone will say that this is exactly according to design and documentation; the service account should have access to the `/nodes` resource. However, at lesat in our case there is a very simple workaround; we can simply use the node name as public name.

To implement this requires an additional try-catch in `KubernetesClient.enrichWithPublicAddresses`:

    String nodeUrl = String.format("%s/api/v1/nodes/%s", kubernetesMaster, node);
    nodePublicIp = extractNodePublicIp(callGet(nodeUrl));

becomes:

    try {
        String nodeUrl = String.format("%s/api/v1/nodes/%s", kubernetesMaster, node);
        nodePublicIp = extractNodePublicIp(callGet(nodeUrl));
    } catch (Exception e2) {
        LOGGER.warning("Failed to find public IP for node, using node name instead: " + node);
        nodePublicIp = node;
    }

Does anyone see any major problem with this change, or could it added in a future release? Should I in that case create a pull request?

### PR DESCRIPTION
**Pull request by henrikarro**
Pull request for issue #146; this adds the flag use-node-name-as-external-address to skip looking up the external IP using the /nodes resource.

fix #146

### CODE REVIEW

**Comment by henrikarro** [comment]
Just noticed I had trailing spaces on a few lines -- I turned off autosave cleanup since it uses different sort order for import statements -- so I pushed a new version. Only affects three lines in KubernetesClientTest and KubernetesConfigTest.

**Comment by mesutcelik** [comment]
verify

**Comment by googlielmo** [comment]
Hi @henrikarro thanks for the PR!
Could you please include user instructions in the README?

**Comment by henrikarro** [comment]
I have updated `README.md` and also made the info message given when using `use-node-name-as-external-address` a bit less threatening. Also updated `.gitignore` with files that Checkstyle and FindBugs created, at least on my machine.

When updating `README.md`, I noticed that the `service-port` property is not documented. I didn't  do anything about this since it's unrelated to #146, but someone might want to look at it.

**Comment by hasancelik** [comment]
> When updating README.md, I noticed that the service-port property is not documented. I didn't do anything about this since it's unrelated to #146, but someone might want to look at it.

Thanks for the catch @henrikarro 👍 I fixed it via https://github.com/hazelcast/hazelcast-kubernetes/commit/d08d198a18f2878839e8d1541984b3eb719638ba

**Comment by googlielmo** [comment]
Thanks @henrikarro for addressing comments, approved!
I pushed a new commit to resolve conflicts.

File: src/main/java/com/hazelcast/kubernetes/KubernetesClient.java [hunk 1]
```diff
@@ -296,15 +299,20 @@ private static String extractZone(JsonObject nodeJson) {
...
-                    String nodePublicIp;
+                    String nodePublicAddress;
                     if (cachedNodePublicIps.containsKey(node)) {
-                        nodePublicIp = cachedNodePublicIps.get(node);
+                        nodePublicAddress = cachedNodePublicIps.get(node);
                     } else {
-                        String nodeUrl = String.format("%s/api/v1/nodes/%s", kubernetesMaster, node);
-                        nodePublicIp = extractNodePublicIp(callGet(nodeUrl));
-                        cachedNodePublicIps.put(node, nodePublicIp);
+                        if (useNodeNameAsExternalAddress) {
```
Comment (leszko) [inline src/main/java/com/hazelcast/kubernetes/KubernetesClient.java]: Minor: consider extracting these 7 lines to a separate method.

File: src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java [hunk 2]
```diff
@@ -437,6 +441,26 @@ public void endpointsByNamespaceWithNodePublicIp() {
         assertThat(formatPublic(result), containsInAnyOrder(ready("35.232.226.200", 31916), ready("35.232.226.201", 31917)));
     }
 
+    @Test
+    public void endpointsByNamespaceWithNodeName() {
+        // given
+        // reuse setup from another test case
+        endpointsByNamespaceWithNodePublicIp();
```
Comment (leszko) [inline src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java]: You call another test in this test, that is not right. Please extract the common parts to a method to reuse.

File: src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java [hunk 3]
```diff
@@ -56,12 +56,16 @@
...
     @Before
     public void setUp() {
-        String kubernetesMasterUrl = String.format("http://%s:%d", KUBERNETES_MASTER_IP, wireMockRule.port());
-        kubernetesClient = new KubernetesClient(NAMESPACE, kubernetesMasterUrl, TOKEN, CA_CERTIFICATE, RETRIES);
+        kubernetesClient = newKubernetesClient(false);
         stubFor(get(urlMatching("/api/.*")).atPriority(5)
                                            .willReturn(aResponse().withStatus(401).withBody("\"reason\":\"Forbidden\"")));
     }
 
+    private KubernetesClient newKubernetesClient(boolean useNodeNameAsExternalAddress) {
```
Comment (leszko) [inline src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java]: 1. Make it static
2. Move this method down, since it's used in multiple places in this class.

Comment (henrikarro) [reply src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java]: The method `newKubernetesClient` uses `wireMockRule`, which I believe cannot be made static, so unfortunately I cannot make the method static unless we provide `wireMockRule` as a parameter.

Which version do you prefer: static method with `wireMockRule` as parameter; or non-static method?

Comment (henrikarro) [reply src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java]: It's only the port number we need from `wireMockRule`, so I can provide the port number as a parameter and make the method static. Then the caller needs to know how to find the port number...

File: src/main/java/com/hazelcast/kubernetes/KubernetesClient.java (hunk 1 above)
Comment (henrikarro) [reply src/main/java/com/hazelcast/kubernetes/KubernetesClient.java]: Annoying fact: when I extract that into a method, CheckStyle complains about `Total number of methods is 31 (max allowed is 30)`.

Any preferences about how to handle this?

Comment (leszko) [reply src/main/java/com/hazelcast/kubernetes/KubernetesClient.java]: lol ;) Add `@SuppressWarnings` for now, we'll have to split this class into multiple classes, but let's not do it in this PR.

Comment (henrikarro) [reply src/main/java/com/hazelcast/kubernetes/KubernetesClient.java]: Method extracted and `@SuppressWarnings("checkstyle:methodcount")` added.

File: src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java (hunk 3 above)
Comment (henrikarro) [reply src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java]: Left it non-static, moved it down to the other helper methods.

File: src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java (hunk 2 above)
Comment (henrikarro) [reply src/test/java/com/hazelcast/kubernetes/KubernetesClientTest.java]: True that. Extracted the JSON for the node port services into helper methods.

**Comment by henrikarro** [comment]
A signed copy of the Contributor Agreement has been sent to cla@hazelcast.com.

**Comment by leszko** [comment]
@henrikarro the PR looks fine. And thanks for signing CLA. One last thing, could you add your parameter `use-node-name-as-external-address` to `KubernetesConfig.toString()`?

**Comment by henrikarro** [comment]
@leszko KubernetesConfig.toString has been updated.

**Comment by leszko** [comment]
@henrikarro FYI: Your change is released in hazelcast-kubernetes 1.5.1.
