### PR TITLE
Fix NPE handling in DnsExndpointResolver

### LINKED ISSUE #120: Fix NullPointerException in DnsEndpointResolver
If no hostname is found, `DnsEndpointResolver` throws `NullPointerException`. We should add a check for null to give a better message to the user.

```

WARNING: [10.128.35.25]:5701 [dev] [3.11] DNS lookup for serviceDns 'hazelcast-service.hazelcast.svc.cluster.local' failed
--
  | java.lang.NullPointerException
  | at com.hazelcast.kubernetes.DnsEndpointResolver.lookup(DnsEndpointResolver.java:89)
  | at com.hazelcast.kubernetes.DnsEndpointResolver.resolve(DnsEndpointResolver.java:76)
  | at com.hazelcast.kubernetes.HazelcastKubernetesDiscoveryStrategy.discoverNodes(HazelcastKubernetesDiscoveryStrategy.java:105)
  | at com.hazelcast.spi.discovery.impl.DefaultDiscoveryService.discoverNodes(DefaultDiscoveryService.java:71)
  | at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddresses(DiscoveryJoiner.java:70)
  | at com.hazelcast.internal.cluster.impl.DiscoveryJoiner.getPossibleAddressesForInitialJoin(DiscoveryJoiner.java:59)
  | at com.hazelcast.cluster.impl.TcpIpJoiner.joinViaPossibleMembers(TcpIpJoiner.java:131)
  | at com.hazelcast.cluster.impl.TcpIpJoiner.doJoin(TcpIpJoiner.java:90)
  | at com.hazelcast.internal.cluster.impl.AbstractJoiner.join(AbstractJoiner.java:135)
  | at com.hazelcast.instance.Node.join(Node.java:767)
  | at com.hazelcast.instance.Node.start(Node.java:411)
  | at com.hazelcast.instance.HazelcastInstanceImpl.<init>(HazelcastInstanceImpl.java:131)
  | at com.hazelcast.instance.HazelcastInstanceFactory.constructHazelcastInstance(HazelcastInstanceFactory.java:202)
  | at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:181)
  | at com.hazelcast.instance.HazelcastInstanceFactory.newHazelcastInstance(HazelcastInstanceFactory.java:131)
  | at com.hazelcast.core.Hazelcast.newHazelcastInstance(Hazelcast.java:57)
  | at com.hazelcast.core.server.StartServer.main(StartServer.java:46)


```

### PR DESCRIPTION
**Pull request by leszko**
fix #120

### CODE REVIEW

File: src/main/java/com/hazelcast/kubernetes/DnsEndpointResolver.java [hunk 1]
```diff
@@ -85,16 +86,18 @@ private static DirContext createDirContext(int serviceDnsTimeout) {
...
         Set<String> addresses = new HashSet<String>();
-        while (servers.hasMore()) {
-            String server = (String) servers.next();
-            String serverHost = extractHost(server);
-            InetAddress address = InetAddress.getByName(serverHost);
-            if (addresses.add(address.getHostAddress()) && logger.isFinestEnabled()) {
-                logger.finest("Found node service with address: " + address);
+        Attributes attributes = dirContext.getAttributes(serviceDns, new String[]{"SRV"});
+        Attribute srvAttribute = attributes.get("srv");
+        if (srvAttribute != null) {
```
Comment (mesutcelik) [inline src/main/java/com/hazelcast/kubernetes/DnsEndpointResolver.java]: I see we saved ourselves from NPE. What happens now when `srvAttribute` now? What is the path?

Comment (leszko) [reply src/main/java/com/hazelcast/kubernetes/DnsEndpointResolver.java]: The only change is in the logs. Before you had a stacktrace with NPE, now you get a message that the service name is not found. It happens when no POD (under the given service) is ready yet. So there is actually no functional change here, the discovery is repeated a few times and then gives up.
